/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lab Informatika
 */
public class perpustakaankita extends javax.swing.JFrame {

    /**
     * Creates new form perpustakaankita
     */
    private static int xx, xy;
    private Connection connection;
    public perpustakaankita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kolomidbuku = new javax.swing.JTextField();
        kolompenerbitbuku = new javax.swing.JTextField();
        kolomstockbuku = new javax.swing.JTextField();
        kolomlokasibuku = new javax.swing.JTextField();
        kolomjudulbuku = new javax.swing.JTextField();
        kolomgenrebuku = new javax.swing.JTextField();
        kolompenulisbuku = new javax.swing.JTextField();
        buttontambah = new javax.swing.JButton();
        buttonubah = new javax.swing.JButton();
        buttontampilkandata = new javax.swing.JButton();
        buttonhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        kolomcaribuku = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttoncari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Perpustakaan Umum Yogyakarta");

        jLabel2.setText("Id buku");

        jLabel3.setText("Judul Buku");

        jLabel4.setText("Genre Buku");

        jLabel5.setText("Penulis Buku");

        jLabel6.setText("Penerbit Buku");

        jLabel7.setText("Lokasi Buku");

        jLabel8.setText("Stock Buku");

        kolomidbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomidbukuActionPerformed(evt);
            }
        });

        kolompenerbitbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolompenerbitbukuActionPerformed(evt);
            }
        });

        kolomstockbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomstockbukuActionPerformed(evt);
            }
        });

        kolomlokasibuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomlokasibukuActionPerformed(evt);
            }
        });

        kolomjudulbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomjudulbukuActionPerformed(evt);
            }
        });

        kolomgenrebuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomgenrebukuActionPerformed(evt);
            }
        });

        kolompenulisbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolompenulisbukuActionPerformed(evt);
            }
        });

        buttontambah.setText("Tambah");
        buttontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontambahActionPerformed(evt);
            }
        });

        buttonubah.setText("Ubah");
        buttonubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonubahActionPerformed(evt);
            }
        });

        buttontampilkandata.setText("Tampilkan Data");
        buttontampilkandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontampilkandataActionPerformed(evt);
            }
        });

        buttonhapus.setText("Hapus");
        buttonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhapusActionPerformed(evt);
            }
        });

        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "judul", "genre", "penulis", "penerbit", "lokasi", "stock"
            }
        ));
        jScrollPane1.setViewportView(tableModel);

        jLabel9.setText("Cari Buku");

        kolomcaribuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomcaribukuActionPerformed(evt);
            }
        });
        kolomcaribuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kolomcaribukuKeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "judul", "gemre", "penulus", "penerbit", "lokasi", "stock" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        buttoncari.setText("Cari");
        buttoncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kolompenulisbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(kolomidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(buttontambah, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(kolomgenrebuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(kolomstockbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kolomlokasibuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kolompenerbitbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttontampilkandata, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonubah, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(kolomjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kolomcaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttoncari)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kolomidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttontambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kolomjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(kolomgenrebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kolompenulisbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolompenerbitbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kolomcaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttoncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonubah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kolomlokasibuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttontampilkandata, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(kolomstockbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolomidbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomidbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomidbukuActionPerformed

    private void kolomjudulbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomjudulbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomjudulbukuActionPerformed

    private void kolomgenrebukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomgenrebukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomgenrebukuActionPerformed

    private void kolompenulisbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolompenulisbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolompenulisbukuActionPerformed

    private void kolompenerbitbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolompenerbitbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolompenerbitbukuActionPerformed

    private void kolomlokasibukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomlokasibukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomlokasibukuActionPerformed

    private void kolomstockbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomstockbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomstockbukuActionPerformed

    private void buttontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontambahActionPerformed
        // TODO add your handling code here:
        connection = Koneksi.getKoneksi();
            String query = "INSERT INTO datapepus"
                    + "(id, judul, genre, harga, penulis. penerbit, lokasi, stock)"
                    + "VALUES (?,?,?,?,?,?,?)";
            try {
                PreparedStatement statement= (PreparedStatement) connection.prepareStatement(query);

                statement.setString(1, judul);
                statement.setString(2, genre);
                statement.setString(3, penulis);
                statement.setString(4, penerbit);
                statement.setString(5, lokasi);
                statement.setString(6, stock);

                statement.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(this, "Kesalahan input data");
            
        }
    }//GEN-LAST:event_buttontambahActionPerformed

    private void buttonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhapusActionPerformed
        // TODO add your handling code here:
         connection = Koneksi.getKoneksi();
        String query = "DELETE FROM dataperpus WHERE id=?";

        try {
            PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);
            statement.setInt(1, this.id);
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat delete data, silahkan coba lagi!");
        }
    }//GEN-LAST:event_buttonhapusActionPerformed

    private void buttonubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonubahActionPerformed
        // TODO add your handling code here:
        int rowCount = tableModel.getRowCount();

        String query = "UPDATE dataperpus SET id = ?, judul = ?, genre=?, penulis=?, penerbit=?, lokasi=?, stock=? WHERE id = ?"; 
       // Replace with your table and column names

        for (int row = 0; row < rowCount; row++) {
            try{
                PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);

                int id = Integer.parseInt((String) tableModel.getValueAt(row, 0));
                String judul = (String) tableModel.getValueAt(row, 1);
                String genre = (String) tableModel.getValueAt(row, 2);
                String penulis = (String) tableModel.getValueAt(row, 3);
                String penerbit = (String) tableModel.getValueAt(row, 4);
                String lokasi = (String) tableModel.getValueAt(row, 5);
                String stock = (String) tableModel.getValueAt(row, 6);
                
                

                statement.setString(1, judul);
                statement.setString(2, genre);
                statement.setString(3, penulis);
                statement.setString(4, penerbit);
                statement.setString(5, lokasi);
                statement.setString(6, stock);
               

                statement.executeUpdate();
            }catch (SQLException e){
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

    }//GEN-LAST:event_buttonubahActionPerformed

    private void buttontampilkandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontampilkandataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabModel;
        ResultSet RsBuku=null;
        try{
            Object[] judul_kolom = {"id", "judul", "genre", "harga", "penulis", "penerbit", "lokasi", "stock"};
            tabModel=new DefaulTableModel(null,judul_kolom);
            tableModel.setModel(tabModel);
            
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsBuku=stt.executeQuery("SELECT * dataperpus ");  
            while(RsBuku.next()){
                Object[] data={
                    RsBuku.getString("id"),
                    RsBuku.getString("judul"),
                    RsBuku.getString("genre"),
                    RsBuku.getString("penulis"),
                    RsBuku.getString("penerbit"),
                    RsBuku.getString("lokasi"),
                    RsBuku.getString("stock"),
                          
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    
    }//GEN-LAST:event_buttontampilkandataActionPerformed

    private void buttoncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttoncariActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void kolomcaribukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomcaribukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomcaribukuActionPerformed

    private void kolomcaribukuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomcaribukuKeyReleased
        // TODO add your handling code here:
        String key=kolombuku.getText();
        System.out.println(key);  
        
        if(key!=""){
            cariData(key);
        }else{
            buttoncaridata();
        }
    }//GEN-LAST:event_kolomcaribukuKeyReleased
    private void  cariData(String key) {
            
            try{
            Object[] judul_kolom = {"id", "judul", "genre", "harga", "penulis", "penerbit", "lokasi", "stock"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            tableModel.setModel(tabModel);
            
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsBuku=stt.executeQuery("SELECT * from dataperpus WHERE id LIKE '%"+key+"%' OR judul LIKE '%"+key+"%' OR genre LIKE '%"+key+"%'");  
            while(RsBuku.next()){
                Object[] data={
                    RsBuku.getString("id"),
                    RsBuku.getString("judul"),
                    RsBuku.getString("genre"),
                    RsBuku.getString("penulis"),
                    RsBuku.getString("penerbit"),
                    RsBuku.getString("lokasi"),
                    RsBuku.getString("stock"),        
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaankita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaankita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaankita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaankita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaankita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncari;
    private javax.swing.JButton buttonhapus;
    private javax.swing.JButton buttontambah;
    private javax.swing.JButton buttontampilkandata;
    private javax.swing.JButton buttonubah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kolomcaribuku;
    private javax.swing.JTextField kolomgenrebuku;
    private javax.swing.JTextField kolomidbuku;
    private javax.swing.JTextField kolomjudulbuku;
    private javax.swing.JTextField kolomlokasibuku;
    private javax.swing.JTextField kolompenerbitbuku;
    private javax.swing.JTextField kolompenulisbuku;
    private javax.swing.JTextField kolomstockbuku;
    private javax.swing.JTable tableModel;
    // End of variables declaration//GEN-END:variables
}

